<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>2 user id</name>
   <tag></tag>
   <elementGuidId>847330ac-9128-4102-b8d5-62de56cb4e20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_userLoginId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_userLoginId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>091b86a8-82fc-4329-b8d1-591adc5f281e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fb50f5a-6c60-4b09-9cb8-0d48cc5438db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uia</name>
      <type>Main</type>
      <value>login-field</value>
      <webElementGuid>2d602762-2072-48b8-91d3-aa760908c32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>userLoginId</value>
      <webElementGuid>69b0e150-0cd9-4f35-940b-258b1ffa6ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nfTextField</value>
      <webElementGuid>83042a9c-d72c-4f0b-b6e2-50f24991fab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_userLoginId</value>
      <webElementGuid>6582c1c2-2cca-445b-9f11-ffa732bb068e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d0d4a711-dd50-40df-9aa8-dc75959a61c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>d807ee94-fb97-4fc4-91bf-72c99f5e52a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dbae9b39-d807-4bb3-a675-43f8022b8b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_userLoginId&quot;)</value>
      <webElementGuid>d58456c7-9188-45aa-b3cb-9bc40c85ce5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_userLoginId']</value>
      <webElementGuid>b50b4569-8c86-4a1b-97fb-df59c8db0f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='appMountPoint']/div/div[3]/div/div/div/form/div/div/div/label/input</value>
      <webElementGuid>f2e4a181-413d-4869-8dc2-e9e47d290449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>6e1a36c0-37b0-4e98-b353-065a4112c9b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'userLoginId' and @id = 'id_userLoginId']</value>
      <webElementGuid>effd8cfd-3c39-41f9-a770-27ced1706d93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
